blueprint:
  name: Motion-Activated Switch or Light
  description: Automatically turn on a light or switch when motion is detected, with adjustable timeout and optional auto-on.
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: List of motion sensors to trigger the automation.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    target_domain:
      name: Target Domain
      description: Choose whether to control a light or switch.
      default: light
      selector:
        select:
          options:
            - light
            - switch
    target_entity:
      name: Target Entity
      description: The light or switch to control.
      selector:
        entity:
          domain:
            - light
            - switch
    auto_on:
      name: Auto-On
      description: Automatically turn on the target when motion is detected.
      default: true
      selector:
        boolean:
    timeout:
      name: Timeout (seconds)
      description: Time in seconds before the target turns off after no motion is detected.
      default: 300
      selector:
        number:
          min: 1
          max: 3600
          step: 1
          unit_of_measurement: s

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input target_entity
            state: "off"
          - condition: template
            value_template: "{{ auto_on }}"
        sequence:
          - service: !input "{{ 'light.turn_on' if target_domain == 'light' else 'switch.turn_on' }}"
            target:
              entity_id: !input target_entity
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensors
        to: "off"
        for:
          seconds: !input timeout
    continue_on_timeout: false
  - service: !input "{{ 'light.turn_off' if target_domain == 'light' else 'switch.turn_off' }}"
    target:
      entity_id: !input target_entity

mode: restart