blueprint:
  name: Motion Activated Switch/Light
  description: >
    This blueprint creates a motion-activated automation for turning on lights or switches
    when motion is detected. It supports multiple sensors and targets (light or switch).
    Option to disable Auto-On and just perform Auto-Off based on timeout settings.

  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: List of motion sensors to trigger the automation.
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    target_entity:
      name: Target Entity
      description: The light or switch to control.
      selector:
        entity:
          domain:
            - light
            - switch

    auto_on_enabled:
      name: Auto-On Enabled
      description: Enable or disable auto-on functionality.
      default: true
      selector:
        boolean: {}

    timeout:
      name: Auto-Off Timeout
      description: Time in seconds before the light or switch is turned off after no motion is detected.
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
          mode: slider

  trigger:
    - platform: state
      entity_id: !input motion_sensors
      to: 'on'

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: !input auto_on_enabled
              state: 'on'
          sequence:
            - service: homeassistant.turn_on
              target:
                entity_id: !input target_entity
    - delay:
        seconds: !input timeout
    - service: homeassistant.turn_off
      target:
        entity_id: !input target_entity
